m4_define(<:xx_img_cheik_zayed:>, <:img/cheikzayed.jpg:>)
m4_define(<:xx_img_burj_khalifa:>, <:img/burj-khalifa.jpg:>)
m4_define(<:xx_img_poterie_meybod:>, <:img/meybod_craftsman.jpg:>)
m4_define(<:xx_img_les_mezzes:>, <:img/mezze.jpg:>)
m4_define(<:xx_img_kess_tey:>, <:img/kesstey.jpg:>)
